=== martijnlaan2/issrc-build-env/ISHelp/isetup.dtd
<!--
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Document Type Definition for isetup.xml
-->

<!ENTITY nbsp   "&#x00A0;">
<!ENTITY copy   "&#x00A9;">
<!ENTITY times  "&#x00D7;">
<!ENTITY divide "&#x00F7;">
<!ENTITY ndash  "&#x2013;">
<!ENTITY mdash  "&#x2014;">
<!ENTITY rarr   "&#x2192;">
<!ENTITY approx "&#x2248;">
<!ENTITY le     "&#x2264;">
<!ENTITY ge     "&#x2265;">

<!ENTITY % _inlineExceptLink "b | br | i | sup | tt | u">
<!ENTITY % _inline "%_inlineExceptLink; | link | extlink | img | a | anchorlink | sd | isxfunc">
<!ENTITY % _block "p | heading | pre | precode | example | examples | indent | ul | ol | dl | paramlist | flaglist | table">
<!ENTITY % _highlight "sec | evt | key | com | con | str | num | ispp">

<!ENTITY % Inline "(#PCDATA | %_inline;)*">
<!ENTITY % InlineExceptLink "(#PCDATA | %_inlineExceptLink;)*">
<!ENTITY % Block "(%_block;)*">
<!ENTITY % InlineOrBlock "(#PCDATA | %_inline; | %_block;)*">
<!ENTITY % InlineWithHighlight "(#PCDATA | %_inline; | %_highlight;)*">
<!ENTITY % InlineOrBlockWithHighlight "(#PCDATA | %_inline; | %_highlight; | %_block;)*">

<!ELEMENT ishelp (contents?, (topic | setuptopic)*)>
<!ATTLIST ishelp version CDATA #REQUIRED>

<!ELEMENT contents ((contentstopic | contentsheading)*)>
<!ELEMENT contentstopic EMPTY>
<!ATTLIST contentstopic title CDATA #REQUIRED topic CDATA #REQUIRED>
<!ELEMENT contentsheading ((contentstopic | contentsheading)*)>
<!ATTLIST contentsheading title CDATA #REQUIRED>

<!ELEMENT topic (keyword*, body)>
<!ATTLIST topic name CDATA #REQUIRED title CDATA #REQUIRED>
<!ELEMENT keyword EMPTY>
<!ATTLIST keyword value CDATA #REQUIRED anchor CDATA #IMPLIED>

<!ELEMENT setuptopic (keyword*, setupformat?, setupvalid?, setupdefault?, body)>
<!ATTLIST setuptopic directive CDATA #REQUIRED title CDATA #IMPLIED>
<!ELEMENT setupformat %Inline;>
<!ELEMENT setupvalid %Inline;>
<!ELEMENT setupdefault %Inline;> 

<!ELEMENT body %Block;>

<!-- Inline elements -->

<!ELEMENT b %Inline;>
<!ELEMENT br EMPTY>
<!ELEMENT i %Inline;>
<!ELEMENT sup %Inline;>
<!ELEMENT tt %InlineWithHighlight;>
<!ELEMENT u %Inline;>
<!ELEMENT link %InlineExceptLink;>
<!ATTLIST link topic CDATA #REQUIRED anchor CDATA #IMPLIED>
<!ELEMENT extlink %InlineExceptLink;>
<!ATTLIST extlink href CDATA #REQUIRED>
<!ELEMENT img %InlineExceptLink;>
<!ATTLIST img src CDATA #REQUIRED>
<!ELEMENT a %InlineExceptLink;>
<!ATTLIST a name CDATA #REQUIRED>
<!ELEMENT anchorlink %InlineExceptLink;>
<!ATTLIST anchorlink name CDATA #REQUIRED>
<!ELEMENT sd %InlineExceptLink;>
<!ELEMENT isxfunc %InlineExceptLink;>

<!-- Syntax highlighting elements -->

<!ELEMENT sec %InlineWithHighlight;>
<!ELEMENT evt %InlineWithHighlight;>
<!ELEMENT key %InlineWithHighlight;>
<!ELEMENT com %InlineWithHighlight;>
<!ELEMENT con %InlineWithHighlight;>
<!ELEMENT str %InlineWithHighlight;>
<!ELEMENT num %InlineWithHighlight;>
<!ELEMENT ispp %InlineWithHighlight;>

<!-- Simple block elements -->

<!ELEMENT p %Inline;>
<!ATTLIST p margin (yes|no) "yes">
<!ELEMENT heading %Inline;>
<!ELEMENT pre %InlineWithHighlight;>
<!ELEMENT precode %InlineWithHighlight;>
<!ELEMENT example %InlineOrBlockWithHighlight;>
<!ATTLIST example noheader CDATA #IMPLIED>
<!ELEMENT examples %InlineOrBlockWithHighlight;>
<!ATTLIST examples noheader CDATA #IMPLIED>
<!ELEMENT indent %Block;>

<!-- Fancier block elements -->

<!ELEMENT ul (li|ul)*>
<!ATTLIST ul appearance (normal|compact) "normal">
<!ELEMENT ol (li*)>
<!ELEMENT li %InlineOrBlock;>

<!ELEMENT dl (dt, dd)*>
<!ELEMENT dt %Inline;>
<!ELEMENT dd %Block;>

<!ELEMENT paramlist (param*)>
<!ELEMENT param %Block;>
<!ATTLIST param name CDATA #REQUIRED required (yes|no) "no">

<!ELEMENT flaglist (flag*)>
<!ELEMENT flag %Block;>
<!ATTLIST flag name CDATA #REQUIRED>

<!ELEMENT table (tr*)>
<!ELEMENT tr (th|td)*>
<!ELEMENT th %InlineOrBlock;>
<!ATTLIST th nowrap CDATA #IMPLIED>
<!ELEMENT td %InlineOrBlock;>
<!ATTLIST td nowrap CDATA #IMPLIED>

=== martijnlaan2/issrc-build-env/ISHelp/isx.xml
<?xml version="1.0" ?>
<!DOCTYPE ishelp SYSTEM "isetup.dtd">

<!--
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.
-->

<ishelp version="1">

<!-- Topics -->

<topic name="scriptintro" title="Pascal Scripting: Introduction">
<keyword value="Pascal Scripting: Introduction" />
<body>

<p>The Pascal scripting feature (modern Delphi-like Pascal) adds lots of new possibilities to customize your Setup or Uninstall at run-time. Some examples:</p>

<ul>
<li>Support for aborting Setup or Uninstall startup under custom conditions.</li>
<li>Support for adding custom wizard pages to Setup at run-time.</li>
<li>Support for extracting and calling DLL or other files from the Pascal script before, during or after the installation.</li>
<li>Support for scripted constants that can do anything the normal constants, the read-from-registry, read-from-ini and read-from-commandline constants can do + more.</li>
<li>Support for run-time removal of types, components and/or tasks under custom conditions.</li>
<li>Support for conditional installation of <tt>[Files]</tt>, <tt>[Registry]</tt>, <tt>[Run]</tt> etc. entries based on custom conditions.</li>
<li>Lots of support functions to do from the Pascal script just about everything Inno Setup itself does/can do + more.</li>
</ul>

<p>An integrated <link topic="scriptdebug">run-time debugger</link> to debug your custom Pascal script is also available.</p>

<p>The scripting engine used by Inno Setup is RemObjects Pascal Script by Carlo Kok. Like Inno Setup, RemObjects Pascal Script is freely available and comes with source. See <extlink href="http://www.remobjects.com/ps">http://www.remobjects.com/ps</extlink> for more information.</p>

<p>Note: the Pascal scripting feature works exclusively at run-time, and has no compile-time functionality.</p>

<heading>Language differences compared to Delphi</heading>

<p>Pascal Script has some language differences compared to Delphi. Key differences include:</p>

<ul>
<li>No inline <tt>var</tt> or inline <tt>const</tt>. All local variables must be declared in a <tt>var</tt> block before <tt>begin</tt>.</li>
<li>No local <tt>const</tt> or <tt>type</tt> declarations. Only <tt>var</tt> and <tt>label</tt> blocks are allowed before <tt>begin</tt>.</li>
<li>No <tt>Exit(Value)</tt> syntax. Assign to <tt>Result</tt> first, then call <tt>Exit</tt> separately.</li>
<li>No typed constants (<tt>const X: Integer = 1</tt>). Only untyped constants (<tt>const X = 1</tt>).</li>
<li>No default parameter values.</li>
<li>No function or procedure overloading.</li>
<li>No <tt>raise</tt> keyword. Use <tt><isxfunc>RaiseException</isxfunc>(Msg)</tt> or <isxfunc>RaiseLastException</isxfunc> instead.</li>
<li>No <tt>on E: ExceptionType do</tt> in <tt>except</tt> blocks. Use <isxfunc>GetExceptionMessage</isxfunc> to inspect the current exception.</li>
<li>No script-defined classes. Classes can be used, but only those defined by Inno Setup.</li>
<li>No variant records.</li>
<li><tt>const</tt> parameters are passed by value (copied), and not by reference as in modern Delphi.</li>
<li>The <tt>/</tt> operator always returns <tt>Extended</tt>, even when both operands are integers. Use <tt>div</tt> for integer division.</li>
<li><tt>Break</tt> and <tt>Continue</tt> are not reserved words. They are ordinary identifiers recognized specially inside loop bodies. A local declaration named <tt>Break</tt> or <tt>Continue</tt> will shadow the loop-control behavior.</li>
<li><isxfunc>Low</isxfunc>, <isxfunc>High</isxfunc>, and <isxfunc>SizeOf</isxfunc> must be used with a variable, not a type.</li>
</ul>

<p><br/><b>See also:</b><br/>
<link topic="scriptcreating">Creating the [Code] section</link><br/>
<link topic="scriptevents">Event Functions</link><br/>
<link topic="scriptconstants">Scripted Constants</link><br/>
<link topic="scriptcheck">Check Parameters</link><br/>
<link topic="scriptinstall">BeforeInstall and AfterInstall Parameters</link><br/>
<link topic="scriptuninstall">Uninstall Code</link><br/>
<link topic="scriptexamples">Examples</link><br/>
<link topic="scriptfunctions">Support Functions Reference</link><br/>
<link topic="scriptclasses">Support Classes Reference</link><br/>
<link topic="scriptpages">Using Custom Wizard Pages</link><br/>
<link topic="scriptdll">Using DLL files</link><br/>
<link topic="scriptautomation">Using COM Automation objects</link><br/>
<link topic="scriptdebug">Run-time debugger</link>
</p>

</body>
</topic>



<topic name="scriptcreating" title="Pascal Scripting: Creating the [Code] Section">
<keyword value="Pascal Scripting: Creating the [Code] Section" />
<keyword value="[Code] section" />
<keyword value="Code" />
<keyword value="{$NOWARN}" />
<body>

<p>The <tt>[Code]</tt> section is an optional section that specifies a Pascal script. A Pascal script can be used to customize Setup or Uninstall in many ways. Note that creating a Pascal script is not easy and requires experience with Inno Setup and knowledge about programming in Pascal or at least a similar programming language.</p>

<p>The <i>Code*.iss</i>, <i>UninstallCode*.iss</i>, and <i>AllPagesExample.iss</i> example scripts in the "Examples" subdirectory in your Inno Setup directory contain various example <tt>[Code]</tt> sections. Please study them carefully before trying to create your own Pascal script.</p>

<p>Note: to learn more about the Pascal programming language you may find it useful to refer to Marco Cant&#249;'s free Essential Pascal book. See <extlink href="http://www.marcocantu.com/epascal/">http://www.marcocantu.com/epascal/</extlink> and <extlink href="https://www.marcocantu.com/epascal/EssentialPascal.zip">https://www.marcocantu.com/epascal/EssentialPascal.zip</extlink>.</p>

<p>To suppress compiler warnings for a line, include a <tt>{$NOWARN}</tt> marker anywhere on that line. It is recognized even inside comments.</p>

</body>
</topic>



<topic name="scriptevents" title="Pascal Scripting: Event Functions">
<keyword value="Pascal Scripting: Event Functions" />
<keyword value="Event Functions" />
<keyword value="Pascal Scripting: Event Attributes" anchor="eventattributes" />
<keyword value="Event Attributes" anchor="eventattributes" />
<keyword value="Attributes" anchor="eventattributes" />
<keyword value="InitializeSetup" anchor="InitializeSetup" />
<keyword value="InitializeWizard" anchor="InitializeWizard" />
<keyword value="DeinitializeSetup" anchor="DeinitializeSetup" />
<keyword value="CurStepChanged" anchor="CurStepChanged" />
<keyword value="CurInstallProgressChanged" anchor="CurInstallProgressChanged" />
<keyword value="NextButtonClick" anchor="NextButtonClick" />
<keyword value="BackButtonClick" anchor="BackButtonClick" />
<keyword value="CancelButtonClick" anchor="CancelButtonClick" />
<keyword value="ShouldSkipPage" anchor="ShouldSkipPage" />
<keyword value="CurPageChanged" anchor="CurPageChanged" />
<keyword value="CheckPassword" anchor="CheckPassword" />
<keyword value="NeedRestart" anchor="NeedRestart" />
<keyword value="UpdateReadyMemo" anchor="UpdateReadyMemo" />
<keyword value="RegisterPreviousData" anchor="RegisterPreviousData" />
<keyword value="CheckSerial" anchor="CheckSerial" />
<keyword value="GetCustomSetupExitCode" anchor="GetCustomSetupExitCode" />
<keyword value="PrepareToInstall" anchor="PrepareToInstall" />
<keyword value="RegisterExtraCloseApplicationsResources" anchor="RegisterExtraCloseApplicationsResources" />
<keyword value="InitializeUninstall" anchor="InitializeUninstall" />
<keyword value="DeinitializeUninstall" anchor="DeinitializeUninstall" />
<keyword value="CurUninstallStepChanged" anchor="CurUninstallStepChanged" />
<keyword value="UninstallNeedRestart" anchor="UninstallNeedRestart" />
<keyword value="InitializeUninstallProgressForm" anchor="InitializeUninstallProgressForm" />
<keyword value="ssPreInstall" anchor="TSetupStep" />
<keyword value="ssInstall" anchor="TSetupStep" />
<keyword value="ssPostInstall" anchor="TSetupStep" />
<keyword value="ssDone" anchor="TSetupStep" />
<keyword value="usAppMutexCheck" anchor="TUninstallStep" />
<keyword value="usUninstall" anchor="TUninstallStep" />
<keyword value="usPostUninstall" anchor="TUninstallStep" />
<keyword value="usDone" anchor="TUninstallStep" />
<keyword value="wpWelcome" anchor="PageID" />
<keyword value="wpLicense" anchor="PageID" />
<keyword value="wpPassword" anchor="PageID" />
<keyword value="wpInfoBefore" anchor="PageID" />
<keyword value="wpUserInfo" anchor="PageID" />
<keyword value="wpSelectDir" anchor="PageID" />
<keyword value="wpSelectComponents" anchor="PageID" />
<keyword value="wpSelectProgramGroup" anchor="PageID" />
<keyword value="wpSelectTasks" anchor="PageID" />
<keyword value="wpReady" anchor="PageID" />
<keyword value="wpPreparing" anchor="PageID" />
<keyword value="wpInstalling" anchor="PageID" />
<keyword value="wpInfoAfter" anchor="PageID" />
<keyword value="wpFinished" anchor="PageID" />
<body>

<p>The Pascal script can contain several event functions which are called at appropriate times.</p>

<heading>Setup event functions</heading>

<p>Setup supports following event functions:</p>

<dl>

<dt><tt>function <a name="InitializeSetup">InitializeSetup</a>: Boolean;</tt></dt>
<dd>
<p>Called during Setup's initialization. Return False to abort Setup, True otherwise.</p>
</dd>

<dt><tt>procedure <a name="InitializeWizard">InitializeWizard</a>;</tt></dt>
<dd>
<p>Use this event function to make changes to the wizard or wizard pages at startup. You can't use the <tt>InitializeSetup</tt> event function for this since at the time it is triggered, the wizard form does not yet exist.</p>
</dd>

<dt><tt>procedure <a name="DeinitializeSetup">DeinitializeSetup</a>;</tt></dt>
<dd>
