=== martijnlaan2/issrc-build-env/ISHelp/ispp.dtd
<!--
  Inno Setup Preprocessor
  Copyright (C) 2001-2002 Alex Yackimoff
  
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Document Type Definition for ispp.xml
-->

<!ENTITY % _inlineExceptLink "b | br | i | tt">
<!ENTITY % _highlight "sec|evt|key|com|con|str|num|ispp">

<!ENTITY % InlineExceptLink "(#PCDATA | %_inlineExceptLink;)*">

<!ELEMENT yasyx     (topic)*>
<!ELEMENT topic     (title|subtopicstitle|keywords|syntax|description|(topic|section)*)+>
<!ATTLIST topic
  id      ID        #IMPLIED
  unlisted (yes|no) "no"
  usetitle (yes|no) "yes">

<!ELEMENT title     (#PCDATA)*>
<!ELEMENT subtopicstitle     (#PCDATA)*>

<!ELEMENT keywords  (kwd)*>
<!ELEMENT kwd       (#PCDATA)*>

<!ELEMENT description (p|pre|table|ul)*>
<!ATTLIST description 
  header (yes|no)   "yes">

<!ELEMENT section (p|pre|table|ul)*>
<!ATTLIST section
  title  CDATA      #REQUIRED>

<!ELEMENT p         (#PCDATA|tt|i|link|extlink|sd|sn)*>
<!ELEMENT pre       (line)*>
<!ELEMENT line      (#PCDATA|link|b|%_highlight;)*>
<!ELEMENT tt        (#PCDATA|b|i|link|extlink)*>
<!ELEMENT link      %InlineExceptLink;>
<!ATTLIST link
  href    CDATA     #IMPLIED
  popup   (yes|no)  "no">
<!ELEMENT extlink   %InlineExceptLink;>
<!ATTLIST extlink
  href    CDATA     #REQUIRED>
<!ELEMENT i         (#PCDATA)*>
<!ELEMENT b         (#PCDATA)*>
<!ELEMENT br        EMPTY>
<!ELEMENT sd        (#PCDATA)*>
<!ELEMENT sn        (#PCDATA)*>

<!ELEMENT sec       (#PCDATA|%_highlight;)*>
<!ELEMENT evt       (#PCDATA|%_highlight;)*>
<!ELEMENT key       (#PCDATA|%_highlight;)*>
<!ELEMENT com       (#PCDATA|%_highlight;)*>
<!ELEMENT con       (#PCDATA|%_highlight;)*>
<!ELEMENT str       (#PCDATA|%_highlight;)*>
<!ELEMENT num       (#PCDATA|%_highlight;)*>
<!ELEMENT ispp      (#PCDATA|%_highlight;)*>

<!ELEMENT syntax (define)*>

<!ELEMENT define (variant|cases|opt|txt|nt|group)*>
<!ATTLIST define 
  id    ID      #IMPLIED
  inline (yes|no) "no">

<!ELEMENT variant (txt|nt|opt|cases|group)*>
<!ATTLIST variant
  br      (yes|no)  "yes">

<!ELEMENT group (txt|nt|opt|group|cases)*>
<!ATTLIST group
  repeated (yes|no) "no">

<!ELEMENT txt (#PCDATA)>
<!ELEMENT nt (#PCDATA)*>
<!ATTLIST nt
  doc    CDATA #IMPLIED
  name   CDATA #IMPLIED>
<!ELEMENT opt (txt|nt|opt|group)*>
<!ATTLIST opt
  repeated (yes|no) "no">

<!ELEMENT cases (case)+>
<!ATTLIST cases
  repeated (yes|no) "no">

<!ELEMENT case (txt|nt|opt|cases)*>

<!ELEMENT table       (tr)*>
<!ELEMENT tr          (th|td)*>
<!ELEMENT th          (#PCDATA|tt)*>
<!ATTLIST th
  nowrap CDATA #IMPLIED>
<!ELEMENT td          (#PCDATA|b|i|link|extlink|table|tt)*>
<!ATTLIST td
  nowrap CDATA #IMPLIED>

<!ELEMENT ul          (li)*>
<!ELEMENT li          (#PCDATA|tt|link|extlink|p|pre)*>

=== martijnlaan2/issrc-build-env/ISHelp/ispp.xml
<?xml version="1.0"?>
<!DOCTYPE yasyx SYSTEM "ispp.dtd" [
 <!ENTITY sp      "&#160;">
 <!ENTITY dsp     "&#160;&#160;">
 <!ENTITY define  '<tt><link href="define">define</link></tt>'>
 <!ENTITY undef   '<tt><link href="undef">undef</link></tt>'>
 <!ENTITY dim     '<tt><link href="dim">dim</link></tt>'>
 <!ENTITY redim   '<tt><link href="dim">redim</link></tt>'>
 <!ENTITY emit    '<tt><link href="emit">emit</link></tt>'>
 <!ENTITY error   '<tt><link href="error">error</link></tt>'>
 <!ENTITY include '<tt><link href="include">include</link></tt>'>
 <!ENTITY insert  '<tt><link href="insert">insert</link></tt>'>
 <!ENTITY pragma  '<tt><link href="pragma">pragma</link></tt>'>
 <!ENTITY file    '<tt><link href="file">file</link></tt>'>
 <!ENTITY ifdef   '<tt><link href="ifdef">ifdef</link></tt>'>
 <!ENTITY ifndef  '<tt><link href="ifdef">ifndef</link></tt>'>
 <!ENTITY ifexist '<tt><link href="ifdef">ifexist</link></tt>'>
 <!ENTITY ifnexist '<tt><link href="ifdef">ifnexist</link></tt>'>
 <!ENTITY if      '<tt><link href="if">if</link></tt>'>
 <!ENTITY elif    '<tt><link href="if">elif</link></tt>'>
 <!ENTITY else    '<tt><link href="if">else</link></tt>'>
 <!ENTITY endif   '<tt><link href="if">endif</link></tt>'>
 <!ENTITY sub     '<tt><link href="sub">sub</link></tt>'>
 <!ENTITY endsub  '<tt><link href="sub">endsub</link></tt>'>
 <!ENTITY for     '<tt><link href="for">for</link></tt>'>
 <!ENTITY env     '<tt><link href="env">env</link></tt>'>
 <!ENTITY expr    '<tt>expr</tt>'> <!-- refers to expression parameters, not the #expr directive -->
 <!ENTITY curtrans '<link href="current-translation">current preprocessor output</link>'>
 <!ENTITY translation '<link href="translation">preprocessor output</link>'>
 <!ENTITY builtins '<link href="builtinsiss">ISPPBuiltins.iss</link>'>
 <!ENTITY dash "&#8211;">
]>
<yasyx>
	<topic id="isppoverview">
		<title>Introduction</title>
		<description header="no">
			<p>The main purpose of Inno Setup Preprocessor (ISPP) is to automate compile-time tasks and avoid repetition in your scripts. For example, you can declare a compile-time preprocessor variable &dash; containing your application name, for instance &dash; and then use its value in several places in your script. If for some reason you need to change the name of your application, you'll have to change it only once in your script. Without the preprocessor, you would need to change all occurrences of your application name throughout the script.</p>
			<p>Another example of using the preprocessor would be gathering version information from your application at compile-time by reading the version info of an EXE file, and using it in your <sd>AppVersion</sd> [Setup] section directive or anywhere else. Without the preprocessor, you would have to modify your script each time the version of your application changes.</p>
			<p>The preprocessor can even scan your source folder and generate script lines for the found files. Without the preprocessor, you would have to manually maintain the list of files.</p>
			<p>The preprocessor can also conditionally include or exclude portions of the script: you can create one single script for different versions of your application (for example, trial versus fully functional). Without the preprocessor, you would need multiple scripts.</p>
			<p>Finally, the preprocessor makes it possible to split long lines using a line spanning symbol.</p>
			<p>Note: the preprocessor works exclusively at compile-time, and has no run-time functionality.</p>
    </description>
		<subtopicstitle>All topics</subtopicstitle>
		<topic id="directives">
			<title>Directives Reference</title>
 			<description header="no">
				<p>There are two kinds of directives in ISPP: simple and inline.</p>
				<p>Simple directives occupy a whole line and begin with the <tt>#</tt> symbol. For example, the following defines a variable called <tt>MyAppName</tt>:</p>
				<pre>
					<line><ispp>#define</ispp> MyAppName <str>"My Program"</str></line>
				</pre>
				<p>Inline directives appear inside other lines and begin with <tt>{#</tt> and end with <tt>}</tt>. For example, the following sets Inno Setup's <sd>AppName</sd> directive to the value of the previously defined variable:</p>
				<pre>
					<line><sec>[Setup]</sec></line>
					<line><key>AppName</key>=<ispp>{#</ispp>MyAppName<ispp>}</ispp></line>
				</pre>
				<p>As seen in the above example, you don't need to specify the name of the &emit; directive when it's used inline, so <tt>{#MyAppName}</tt> is short for <tt>{#emit MyAppName}</tt>.</p>
			</description>
			<section title="Directive syntax documenting conventions">
				<p>Directive usage syntax uses the following conventions.</p>
				<table>
					<tr><td><code>()</code></td><td>Group of tokens.</td></tr>
					<tr><td><code>[]</code></td><td>Optional token or group of tokens.</td></tr>
					<tr><td><code>|</code></td><td>Mutually exclusive tokens.</td></tr>
					<tr><td><code>...</code></td><td>Previous token or group of tokens can be repeated.</td></tr>
					<tr><td><code><b>token</b></code></td><td>Reserved word or symbol(s). Must be typed exactly as shown.</td></tr>
					<tr><td><code>&lt;token&gt;</code></td><td>Non-terminal. Its syntax is either shown before, or explained.</td></tr>
				</table>
			</section>
			<subtopicstitle>Available directives</subtopicstitle>
			<topic id="define">
				<title>#define</title>
				<keywords>
          <kwd>#:</kwd>
          <kwd>define</kwd>
        </keywords>
				<syntax>
					<define id="define-directive">
						<variant><nt name="variable-definition"/></variant>
						<variant><nt name="function-definition"/></variant>
						<variant><nt name="default-visibility-set"/></variant>
					</define>
					<define id="variable-definition">
						<group><nt name="define-dir-name"/></group><opt><nt name="locality"/></opt><nt>ident</nt><opt><nt name="index-spec"/></opt><opt><opt><txt>=</txt></opt><nt>expr</nt></opt>
					</define>
					<define id="function-definition">
						<group><nt name="define-dir-name"/></group><opt><nt name="locality"/></opt><nt>ident</nt><txt>(</txt><opt><nt name="formal-function-args"/></opt><txt>)</txt><nt>expr</nt>
					</define>
					<define id="default-visibility-set">
						<group><nt name="define-dir-name"/></group><nt name="locality"/>
					</define>
					<define id="define-dir-name" inline="yes">
						<cases>
							<case><txt>define</txt></case>
							<case><txt>:</txt></case>
						</cases>
					</define>
					<define id="formal-function-args">
						<nt name="formal-function-arg"/><opt repeated="yes"><txt>,</txt><nt name="formal-function-arg"/></opt>
					</define>
					<define id="formal-function-arg">
						<cases>
							<case><nt name="by-val-arg"/></case>
							<case><nt name="by-ref-arg"/></case>
						</cases>
					</define>
					<define id="by-val-arg">
						<variant><opt><nt name="value-type-id"/></opt><nt>ident</nt><opt><txt>=</txt><nt>expr</nt></opt></variant>
						<variant><nt name="func-or-array-type-id"/><nt>ident</nt></variant>
					</define>
					<define id="by-ref-arg">
						<opt><nt name="value-type-id"/></opt><txt>*</txt><nt>ident</nt>
					</define>
					<define id="value-type-id">
						<cases>
							<case><txt>any</txt></case>
							<case><txt>int</txt></case>
							<case><txt>str</txt></case>
						</cases>
					</define>
					<define id="func-or-array-type-id">
						<cases>
							<case><txt>func</txt></case>
							<case><txt>array</txt></case>
						</cases>
					</define>
					<define id="locality" inline="yes">
						<cases>
							<case><txt>private</txt></case>
							<case><txt>protected</txt></case>
							<case><txt>public</txt></case>
						</cases>
					</define>
				</syntax>
				<description>
					<p>The first syntax ("variable-definition") defines a variable named <tt>ident</tt>, or assigns a value to an element of an array named <tt>ident</tt> (use &dim; instead of <tt>define</tt> to define the array variable itself). If none of the <tt>public</tt>, <tt>protected</tt>, or <tt>private</tt> keywords are specified, default <link href="visibility">visibility</link> is assumed.</p>
					<p>The second syntax ("function-definition") defines <link href="macros">a user defined function</link> named <tt>ident</tt>. Note:</p>
					<ul>
						<li>There must be no whitespace between the name and the opening parenthesis, otherwise it will be treated as a variable declaration.</li>
						<li>Formal parameters may be preceded by a type-id: <tt>any</tt>, <tt>int</tt>, <tt>str</tt>, <tt>func</tt>, or <tt>array</tt>.</li>
						<li>Default values may be specified only for parameters with no type-id or with type-id: <tt>any</tt>, <tt>int</tt>, or <tt>str</tt>.</li>
						<li>The <tt>func</tt> type-id declares that the parameter accepts a user defined function or built-in function, and the <tt>array</tt> type-id declares that it accepts an array variable. When calling such a user defined function, the actual parameter for a <tt>func</tt> or <tt>array</tt> parameter must be specified using the <tt>@</tt> operator (for example, <tt>@MyFunc</tt> or <tt>@MyArray</tt>). Also see <link href="macros">User Defined Functions</link>.</li>
					</ul>
					<p>The third syntax ("default-visibility-set") sets the default <link href="visibility">visibility</link> of further variable and user defined function definitions in this file. If no visibility declaration occurs in a file, public visibility is assumed by default.</p>
				</description>
				<section title="Examples">
					<pre>
						<line><ispp>#define</ispp> MyAppName <str>"My Program"</str></line>
						<line><ispp>#define</ispp> MyAppExe MyAppName + <str>".exe"</str></line>
						<line><ispp>#define</ispp> MyAppVer <link href="GetVersionNumbersString">GetVersionNumbersString</link>(MyAppExe)</line>
